---

- name: Configure Logstash pipelines
  template:
    src: "{{ item.value.template | default('logstash.conf.j2') }}"
    dest: '{{ logstash_config_path }}/{{ item.key }}.conf'
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0644
  with_dict: '{{ logstash_configs }}'
  notify: restart logstash
