---

- name: Ensure Logstash config directory exist
  file:
    path: '{{ logstash_config_path }}'
    state: directory
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0775

- name: Configuring Logstash
  template:
    src: '{{ item }}.conf.j2'
    dest: '{{ logstash_config_path }}/{{ item }}.conf'
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0644
  with_items: '{{ logstash_base_configs }}'
  notify:
    - restart logstash

- name: Ensure logstash pattern folders exist
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0775
    recurse: yes
  with_items:
    - /usr/share/logstash/lib/logstash/outputs/elasticsearch
    - /usr/share/logstash/patterns
  notify:
    - restart logstash
