---

- name: Ensure Logstash config directory exist
  file:
    path: '{{ logstash_config_path }}'
    state: directory
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0775

- name: Configuring Logstash
  template:
    src: "{{ item.value.template | default('logstash.conf.j2') }}"
    dest: '{{ logstash_config_path }}/{{ item.key }}.conf'
    owner: '{{ logstash_user }}'
    group: '{{ logstash_user }}'
    mode: 0644
  with_dict: '{{ logstash_configs }}'
  notify: restart logstash
