---

- name: Get list of installed plugins.
  shell: bin/logstash-plugin list
  args:
    chdir: '{{ logstash_path }}'
  register: logstash_plugins_installed
  changed_when: false

- name: Install configured plugins.
  shell: bin/logstash-plugin install '{{ item }}'
  become: yes
  args:
    chdir: '{{ logstash_path }}'
  with_items: '{{ logstash_plugins }}'
  when: 'item not in logstash_plugins_installed.stdout'
